// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Lq506Yph8VUCIOIU2gYiynkxhQ7T0HI',
    appId: '1:885286614679:web:b77ffee17e71c874421bd2',
    messagingSenderId: '885286614679',
    projectId: 'fluxmarket-3e6b9',
    authDomain: 'fluxmarket-3e6b9.firebaseapp.com',
    storageBucket: 'fluxmarket-3e6b9.firebasestorage.app',
    measurementId: 'G-51J1KWH8CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABRYYkvKvQgpah6yNbakiT3YxmY5qwBok',
    appId: '1:885286614679:android:fce87de6576a973d421bd2',
    messagingSenderId: '885286614679',
    projectId: 'fluxmarket-3e6b9',
    storageBucket: 'fluxmarket-3e6b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeC45qcPWwcWVqZjwWObjozlp1k1-2ABE',
    appId: '1:885286614679:ios:c15acf1e467322d5421bd2',
    messagingSenderId: '885286614679',
    projectId: 'fluxmarket-3e6b9',
    storageBucket: 'fluxmarket-3e6b9.firebasestorage.app',
    iosBundleId: 'com.example.fluxmarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeC45qcPWwcWVqZjwWObjozlp1k1-2ABE',
    appId: '1:885286614679:ios:c15acf1e467322d5421bd2',
    messagingSenderId: '885286614679',
    projectId: 'fluxmarket-3e6b9',
    storageBucket: 'fluxmarket-3e6b9.firebasestorage.app',
    iosBundleId: 'com.example.fluxmarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Lq506Yph8VUCIOIU2gYiynkxhQ7T0HI',
    appId: '1:885286614679:web:e27de2cf90e8b773421bd2',
    messagingSenderId: '885286614679',
    projectId: 'fluxmarket-3e6b9',
    authDomain: 'fluxmarket-3e6b9.firebaseapp.com',
    storageBucket: 'fluxmarket-3e6b9.firebasestorage.app',
    measurementId: 'G-5SYEKHWMY6',
  );
}
